language      : php
php           : [7.1, 7.2]
cache         : { directories : [$COMPOSER_CACHE_DIR, $HOME/.composer/cache, vendor] }
install       : composer update --no-interaction --prefer-dist
notifications :
  email : false

stages :
- test
- lint

script :
- vendor/bin/phpunit

before_install :
- composer global require hirak/prestissimo --update-no-dev

jobs :
  include :
  - stage : lint
    php   : 7.2
    env   : TESTBENCH_VERSION=3.6.* LARAVEL_VERSION=5.6.*
    before_install :
    - composer global require hirak/prestissimo --update-no-dev
    - composer require phpmd/phpmd --no-update --prefer-dist
    - composer require phpstan/phpstan --no-update --prefer-dist
    script :
    - vendor/bin/phpmd src text phpmd.xml
    - vendor/bin/phpmd tests text phpmd.xml
    - vendor/bin/phpstan analyse --autoload-file=_ide_helper.php --level 1 src